### ISSUE TITLE
gitでは具体的に何をするのでしょうか

### ISSUE THREAD

**Issue by temmie3** [Stealthmate/saidai-deep-learning#1]
私、気になります！

**Comment by temmie3** [comment]
gitは、プログラムのソースコードなどの変更履歴を記録・追跡するための分散型バージョン管理システムである。Linuxカーネルのソースコード管理に用いるためにリーナス・トーバルズによって開発され、それ以降ほかの多くのプロジェクトで採用されている。

**Comment by Stealthmate** [comment]
基本情報良く勉強して来ましたね！

直近で言うと、今後いろいろソースコードをアップするのでそれを落としてもらったりする。

一般的に言うと、ソースコードをいじった時に、何をいついじったかがわかってると、後からそれがバグになったら探しやすいので、そういう意味でバージョン管理をする。それから、複数人が同じソフトを作る時に、みんなの変更を個別に観たり、レビューしたり、合併したりするために使う。そのうちこれもやってみたい気持ちはあるけど、どういう風に組み入れるかは考えてない。

**Comment by temmie3** [comment]
gitはみんなでコードを編集したり、管理するときに役立つという認識でよいのでしょうか？

**Comment by temmie3** [comment]
基本情報はgitではなくp***の方ですね

**Comment by Stealthmate** [comment]
そのとおり

**Comment by temmie3** [comment]
ありがとう
